# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0015_auto_20160217_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '1. \u10e4\u10d0\u10d8\u10da\u10d8', 'verbose_name_plural': '1. \u10e4\u10d0\u10d8\u10da\u10d4\u10d1\u10d8'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='name20',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='url',
            new_name='name21',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ip',
        ),
        migrations.AddField(
            model_name='customer',
            name='body',
            field=models.TextField(default=1, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
