# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0016_auto_20160217_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='body',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name20',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name21',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
