# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0017_auto_20160217_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Reference_Number', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': '1. \u10db\u10d4\u10e1\u10d8\u10ef\u10d8',
                'verbose_name_plural': '1. \u10db\u10d4\u10e1\u10d8\u10ef\u10d8',
            },
        ),
        migrations.CreateModel(
            name='MSG_COMMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Related_Reference', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': '1. \u10db\u10d4\u10e1\u10d8\u10ef\u10d8\u10e1 \u10de\u10d0\u10e1\u10e3\u10ee\u10d8',
                'verbose_name_plural': '1. \u10db\u10d4\u10e1\u10d8\u10ef\u10d8\u10e1 \u10de\u10d0\u10e1\u10e3\u10ee\u10d8',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
