# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0018_auto_20160217_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='body',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
