# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0019_msg_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='Transaction_Reference_Number',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='msg',
            name='body',
            field=models.TextField(blank=True, max_length=8000),
        ),
    ]
