# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0022_auto_20160218_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='Transaction_Reference_Number',
            new_name='file_name',
        ),
    ]
